### ISSUE TITLE
Download genomic region using BED file as input

### ISSUE THREAD

**Issue by hubentu** [EGA-archive/ega-download-client#140]
Hi @jml96 @malloryfreeberg ,

I got the same error when trying to download BAM in a genomic region from EGAD00001001039. Could you please help me to check this issue? Is this caused by missing index files or is this feature not supported anymore?
btw. is there a feature to download a subset of BAM with a bed file?

Thanks,
Qiang

_Originally posted by @hubentu in https://github.com/EGA-archive/ega-download-client/issues/65#issuecomment-992928913_

**Comment by malloryfreeberg** [comment]
Hi @hubentu - Thanks for the question. Indeed, when I look at the list of files for that dataset (go to the dataset on the EGA website [here](https://ega-archive.org/datasets/EGAD00001001039/files) and click "Download as CSV"), I do not see any BAM index files (i.e. .bai files). This means that genomic slicing is not possible for the files in this dataset.

> is there a feature to download a subset of BAM with a bed file?

Do you mean that, instead of supplying the pyega3 command with chr, start, and end position, instead you supply a bed file of genomic regions, each of which triggers a call to pyega3 to download that region?

**Comment by hubentu** [comment]
Hi @malloryfreeberg , Thank you for confirming this issue. And yes, similiar to `samtools view -L`, the bed option can help to extract reads overlapping multiple genomic regions.

**Comment by CsabaHalmagyi** [comment]
Supporting this feature is not planned currently.
