### ISSUE TITLE
Is support for gpg files planned?

### ISSUE THREAD

**Issue by zichner** [EGA-archive/ega-download-client#20]
The python based ega client version 3 seems to have many advantages over the version 2 client, but unfortunately, gpg files are currently not supported.

Is support for gpg files planned and if so, is there an estimate when this will be?

Thank you very much!

**Comment by AlexanderSenf** [comment]
The path to resolve this issue is actually to change to archive to re-encrypt objects stored in gpg format with ones encrypted in AES (CIP), which will make them available to the Python client. Much of the functionality offered by the Python client requires files to be random-accessible while they are encrypted, which is not possible with gpg files.

I don't have a definite timeline, however. At this point the re-encryption process should have been started. The plan is to proceed based on which datasets are most requested.

**Comment by zichner** [comment]
Thanks for the information!
