### ISSUE TITLE
does htsget work?

### ISSUE THREAD

**Issue by EvanTheB** [EGA-archive/ega-download-client#30]
Hello,

I have had a ticket with the ega helpdesk for 4 months asking about the htsget api (304691). Maybe you can help me.

The htsget api seems to not work. This works:

    pyega3 -d -cf ~/.ega2 fetch EGAF0000xxx

This fails:

    pyega3 -d -cf ~/.ega2 fetch EGAF0000xxx --reference-name 1 --start 100000 --end 200000

The error code is a 500 server error.

https://www.biostars.org/p/367940/

**Comment by AlexanderSenf** [comment]
So.. htsget does work, but not for all files in the EGA archive. The issue is that a lot of files in EGA pre-date htsget, and htsget requires information in the archive that is not available for every file. So, while the code does work, the archive it not able to process requests for all files.

Could you please contact the EGA helpdesk directly regarding the files you are trying to access, then we can validate their status in the archive, and determine what exactly caused the errors you are experiencing.

Thank you. If the error is tied to the code itself I will re-open the issue.
