### ISSUE TITLE
Client secret

### ISSUE THREAD

**Issue by EvanTheB** [EGA-archive/ega-download-client#31]
Hello,

I was told by the ega helpdesk to use the client secret:

        "AMenuDLjVdVo4BSwi0QD54LL6NeVDEZRzEQUJ7hJOM3g4imDZBHHX0hNfKHPeQIGkskhtCmqAJtt_jm7EKq-rWw"

Which I now see is the exact 'secret' that you use on this page. Is this a secret? What is the secret used for?

Thanks

**Comment by AlexanderSenf** [comment]
This secret is used to allow the download client access to the EGA AAI, in order to authenticate you against the EGA user database in a secure way. This is a standard process with OpenID Connect/OAuth2. It is essentially the client's permission to contact the EGA AAI (it wouldn't be feasible to register each person using the client with an individual client id/secret; at least not at the moment).

Please re-open the issue if you have any more questions.
