### ISSUE TITLE
Failed to establish a new connection: [Errno 111] Connection refused',)

### ISSUE THREAD

**Issue by biobug16** [EGA-archive/ega-download-client#71]
Hi @anandmohan777 , @AlexanderVi and rest all,

I am trying to use pyeg3 to download a dataset from EGA, but getting an error

`requests.exceptions.ConnectionError: HTTPSConnectionPool(host='ega.ebi.ac.uk', port=8443): Max retries exceeded with url: /ega-openid-connect-server/token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb07eee6c88>: Failed to establish a new connection: [Errno 111] Connection refused',))`

Can you please help or guide how to resolve this issue.
Thanks

**Comment by marzamKI** [comment]
Hi,

I also seem to have a problem with the connection, despite being able to download data a few weeks ago.. Any thoughts?

`requests.exceptions.ConnectionError: HTTPSConnectionPool(host='ega.ebi.ac.uk', port=8443): Max retries exceeded with url: /ega-openid-connect-server/token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x1020badc0>: Failed to establish a new connection: [Errno 60] Operation timed out'))`

Thank you,
Margherita

**Comment by stsergbg** [comment]
Hi, 

I have the same issue but I suppose the reason is listed on [ega archive website](https://ega-archive.org/):

![image](https://user-images.githubusercontent.com/48471789/77534139-2e16dc80-6ea9-11ea-8ac8-d53a7a6b52e2.png)

I guess there might be no way of getting files at least until 3.01, I've tried pyega3, the java client and the direct API - all with no result.

**Comment by GiselleMarie** [comment]
Hi,

This is a service issue - and not related to the Client. For further assistance please contact the EGA helpdesk on helpdesk@ega-archive.org or further advice.

Thanks.

**Comment by malloryfreeberg** [comment]
Hi @biobug16, @stsergbg, and @marzamKI ,

Thank you for reporting these issues. The EMBL-EBI data centre migration has been completed. If you are still experiencing this issue, please run your command(s) using the -d debug flag - which will generate a log - and email the log to the EGA Helpdesk at helpdesk@ega-archive.org for further assistance.

Thank you!
